# Generated by Django 3.2.13 on 2022-08-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fullcombined',
            fields=[
                ('service_order', models.BigIntegerField(db_column='SERVICE_ORDER', primary_key=True, serialize=False)),
                ('service_order_user_status', models.CharField(blank=True, db_column='SERVICE_ORDER_USER_STATUS', max_length=50, null=True)),
                ('notification_user_status', models.CharField(blank=True, db_column='NOTIFICATION_USER_STATUS', max_length=50, null=True)),
                ('priority_text', models.CharField(blank=True, db_column='PRIORITY_TEXT', max_length=50, null=True)),
                ('mat', models.CharField(blank=True, db_column='MAT', max_length=50, null=True)),
                ('customer_po_number', models.CharField(blank=True, db_column='CUSTOMER_PO_NUMBER', max_length=50, null=True)),
                ('initial_po_number', models.CharField(blank=True, db_column='Initial_PO_Number', max_length=1, null=True)),
                ('mo_number', models.FloatField(blank=True, db_column='MO_NUMBER', null=True)),
                ('equipment_description', models.CharField(blank=True, db_column='EQUIPMENT_DESCRIPTION', max_length=50, null=True)),
                ('model_number', models.CharField(blank=True, db_column='MODEL_NUMBER', max_length=50, null=True)),
                ('serial_no', models.CharField(blank=True, db_column='SERIAL_NO', max_length=50, null=True)),
                ('mal_start', models.DateField(db_column='MAL_START')),
                ('required_start_date', models.DateField(db_column='Required_Start_Date')),
                ('required_end_date', models.DateField(blank=True, db_column='Required_End_Date', null=True)),
                ('reported_fault_long_text', models.CharField(blank=True, db_column='Reported_Fault_Long_Text', max_length=50, null=True)),
                ('capacity_hour', models.FloatField(blank=True, db_column='CAPACITY_HOUR', null=True)),
                ('enduser', models.CharField(blank=True, db_column='ENDUSER', max_length=50, null=True)),
                ('main_work_center', models.CharField(db_column='MAIN_WORK_CENTER', max_length=50)),
                ('ctat', models.FloatField(blank=True, db_column='CTAT', null=True)),
                ('calculated_ctat', models.CharField(blank=True, db_column='Calculated_CTAT', max_length=50, null=True)),
                ('approval_status', models.CharField(db_column='APPROVAL_STATUS', max_length=50)),
                ('a_w_spare', models.SmallIntegerField(db_column='A_W_SPARE')),
                ('a_w_facility', models.SmallIntegerField(db_column='A_W_FACILITY')),
                ('a_w_other_job', models.SmallIntegerField(db_column='A_W_OTHER_JOB')),
                ('inst', models.SmallIntegerField(db_column='INST')),
                ('oth', models.SmallIntegerField(db_column='OTH')),
                ('await_unit_accept', models.SmallIntegerField(db_column='AWAIT_UNIT_ACCEPT')),
                ('multiple_faults', models.SmallIntegerField(db_column='MULTIPLE_FAULTS')),
                ('actual_tat', models.SmallIntegerField(db_column='Actual_TAT')),
                ('tet', models.SmallIntegerField(db_column='TET')),
                ('calculated_ctat2', models.FloatField(blank=True, db_column='Calculated_CTAT2', null=True)),
                ('out_by', models.FloatField(blank=True, db_column='Out_By', null=True)),
                ('job_status', models.CharField(db_column='Job_status', max_length=50)),
            ],
            options={
                'db_table': 'FullCombined',
                'managed': False,
            },
        ),
    ]
