# Generated by Django 4.0.4 on 2022-06-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20210422_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='phone',
            new_name='system_id',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='name',
            new_name='system_name',
        ),
    ]
