# Generated by Django 4.0.4 on 2022-06-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_rename_dicrepancy_report_discrepancy_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval_for_work',
            name='id',
        ),
        migrations.AddField(
            model_name='approval_for_work',
            name='AFW_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discrepancy_report',
            name='cause_of_delay',
            field=models.CharField(choices=[('Parts Missing', 'Parts Missing'), ('Equipment Faulty', 'Equipment Faulty'), ('To be assessed for OEM repair', 'To be assessed for OEM repair'), ('Pending further evaluation', 'Pending further evaluation'), ('Priority given to others', 'Priority given to others')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discrepancy_report',
            name='expected_delay_duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
