# Generated by Django 4.0.4 on 2022-06-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_remove_approval_for_work_id_approval_for_work_afw_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_status',
            name='priority',
            field=models.CharField(choices=[('AOG', 'AOG'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('NA', 'NA')], max_length=200, null=True),
        ),
    ]
