# Generated by Django 4.0.5 on 2022-06-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_job_status_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Send_email',
        ),
        migrations.AlterField(
            model_name='job_status',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=200, null=True),
        ),
    ]
