# Generated by Django 4.0.4 on 2022-06-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_job_status_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_status',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=200, null=True),
        ),
    ]
