# Generated by Django 4.0.4 on 2022-06-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_job_status_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip220610Cleaned',
            fields=[
                ('service_ord', models.BigIntegerField(db_column='SERVICE_ORD', primary_key=True, serialize=False)),
                ('service_order_user_status', models.CharField(db_column='SERVICE_ORDER_USER_STATUS', max_length=50)),
                ('notification_user_status', models.CharField(db_column='NOTIFICATION_USER_STATUS', max_length=50)),
                ('priority', models.CharField(db_column='Priority', max_length=50)),
                ('mat', models.CharField(db_column='MAT', max_length=50)),
                ('customer_po_number', models.BigIntegerField(blank=True, db_column='CUSTOMER_PO_NUMBER', null=True)),
                ('initial_po_number', models.CharField(blank=True, db_column='Initial_PO_Number', max_length=1, null=True)),
                ('mo_number', models.BigIntegerField(blank=True, db_column='MO_NUMBER', null=True)),
                ('equipment_description', models.CharField(blank=True, db_column='EQUIPMENT_DESCRIPTION', max_length=50, null=True)),
                ('model_number', models.CharField(blank=True, db_column='MODEL_NUMBER', max_length=50, null=True)),
                ('serial_no', models.CharField(blank=True, db_column='SERIAL_NO', max_length=50, null=True)),
                ('date_in', models.DateField(db_column='DATE_IN')),
                ('required_start_date', models.DateField(db_column='Required_Start_Date')),
                ('required_end_date', models.DateField(blank=True, db_column='Required_End_Date', null=True)),
                ('reported_fault_long_text', models.CharField(blank=True, db_column='Reported_Fault_Long_Text', max_length=50, null=True)),
                ('capacity_hour', models.FloatField(db_column='CAPACITY_HOUR')),
                ('enduser', models.CharField(blank=True, db_column='ENDUSER', max_length=50, null=True)),
                ('main_work_center', models.CharField(db_column='MAIN_WORK_CENTER', max_length=50)),
                ('ctat', models.SmallIntegerField(db_column='CTAT')),
                ('sample_tat', models.DateTimeField(db_column='Sample_TAT')),
                ('sampletatdate', models.DateField(blank=True, db_column='SampleTATDate', null=True)),
            ],
            options={
                'db_table': 'IP_220610_Cleaned',
            },
        ),
    ]
