# Generated by Django 4.0.4 on 2022-06-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_ip220610cleaned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip220610cleaned',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='discrepancy_report',
            name='service_order_number',
        ),
        migrations.AddField(
            model_name='discrepancy_report',
            name='discrepancy_creation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='discrepancy_report',
            name='service_ord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ip220610cleaned'),
        ),
    ]
