# Generated by Django 4.0.4 on 2022-06-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_alter_ip220610cleaned_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval_for_work',
            name='service_order_number',
        ),
        migrations.AddField(
            model_name='approval_for_work',
            name='discrepancy_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.discrepancy_report'),
        ),
        migrations.AddField(
            model_name='approval_for_work',
            name='service_ord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ip220610cleaned'),
        ),
    ]
