# Generated by Django 4.0.4 on 2022-06-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_approval_for_work_approval_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_update_complete',
            fields=[
                ('service_ord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.ip220610cleaned')),
                ('mal_end_date', models.DateTimeField(null=True)),
                ('job_complete_input', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_update_start',
            fields=[
                ('job_update_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cause_of_delay', models.CharField(choices=[('A/W SPARE', 'A/W SPARE'), ('A/W FACILITY', 'A/W FACILITY'), ('A/W OTHER JOB', 'A/W OTHER JOB'), ('OTH', 'OTH'), ('AWAIT UNIT ACCEPT', 'AWAIT UNIT ACCEPT'), ('MULTIPLE FAULTS', 'MULTIPLE FAULTS')], max_length=200, null=True)),
                ('start_date_actual', models.DateTimeField(null=True)),
                ('start_date_input', models.DateTimeField(null=True)),
                ('service_ord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ip220610cleaned')),
            ],
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='AuditScore',
        ),
        migrations.RemoveField(
            model_name='covidcompliancechecklist',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='covidreport',
            name='compliance',
        ),
        migrations.RemoveField(
            model_name='covidreport',
            name='store',
        ),
        migrations.RemoveField(
            model_name='fbchecklist',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='fbreport',
            name='compliance',
        ),
        migrations.RemoveField(
            model_name='fbreport',
            name='store',
        ),
        migrations.RemoveField(
            model_name='nonfbchecklist',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='nonfbreport',
            name='compliance',
        ),
        migrations.RemoveField(
            model_name='nonfbreport',
            name='store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Covid_Compliance_Report',
        ),
        migrations.RemoveField(
            model_name='order',
            name='FB_Report',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Non_FB_Report',
        ),
        migrations.RemoveField(
            model_name='order',
            name='covid_compliance',
        ),
        migrations.RemoveField(
            model_name='order',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.DeleteModel(
            name='Send_email',
        ),
        migrations.DeleteModel(
            name='Statistics_page',
        ),
        migrations.RemoveField(
            model_name='store',
            name='tags',
        ),
        migrations.CreateModel(
            name='job_update_end',
            fields=[
                ('job_update_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.job_update_start')),
                ('end_date_actual', models.DateTimeField(null=True)),
                ('end_date_input', models.DateTimeField(null=True)),
                ('service_ord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ip220610cleaned')),
            ],
        ),
        migrations.DeleteModel(
            name='CovidComplianceChecklist',
        ),
        migrations.DeleteModel(
            name='CovidReport',
        ),
        migrations.DeleteModel(
            name='FBChecklist',
        ),
        migrations.DeleteModel(
            name='FBReport',
        ),
        migrations.DeleteModel(
            name='NonFBChecklist',
        ),
        migrations.DeleteModel(
            name='NonFBReport',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
