# Generated by Django 3.2.13 on 2022-06-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_announcement_auditscore_covidcompliancechecklist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_update_complete',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='job_update_end',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='job_update_start',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='job_update_complete',
            name='job_update_id',
            field=models.BigIntegerField(db_column='Jobupdateid', null=True),
        ),
        migrations.AlterField(
            model_name='job_update_complete',
            name='job_complete_input',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_update_complete',
            name='mal_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_update_complete',
            name='service_ord',
            field=models.BigIntegerField(db_column='Service_Order', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job_update_end',
            name='end_date_actual',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job_update_end',
            name='end_date_input',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job_update_end',
            name='job_update_id',
            field=models.BigIntegerField(db_column='Jobupdateid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job_update_end',
            name='service_ord',
            field=models.BigIntegerField(db_column='Service_Order'),
        ),
        migrations.AlterField(
            model_name='job_update_start',
            name='cause_of_delay',
            field=models.CharField(db_column='Cause_of_Delay', max_length=50),
        ),
        migrations.AlterField(
            model_name='job_update_start',
            name='job_update_id',
            field=models.BigIntegerField(db_column='Jobupdateid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job_update_start',
            name='service_ord',
            field=models.BigIntegerField(db_column='SERVICE_ORD'),
        ),
        migrations.AlterField(
            model_name='job_update_start',
            name='start_date_actual',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job_update_start',
            name='start_date_input',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='job_update_complete',
            table='job_update_complete',
        ),
        migrations.AlterModelTable(
            name='job_update_end',
            table='job_update_end',
        ),
        migrations.AlterModelTable(
            name='job_update_start',
            table='job_update_start',
        ),
    ]
