# Generated by Django 3.2.13 on 2022-06-20 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20220620_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_update_complete_mock',
            fields=[
                ('service_ord', models.BigIntegerField(db_column='Service_Order', primary_key=True, serialize=False)),
                ('job_update_id', models.BigIntegerField(db_column='Jobupdateid', null=True)),
                ('mal_end_date', models.DateField(blank=True, null=True)),
                ('job_complete_input', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_update_complete',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='job_update_end_mock',
            fields=[
                ('service_ord', models.BigIntegerField(db_column='Service_Order')),
                ('job_update_id', models.BigIntegerField(db_column='Jobupdateid', primary_key=True, serialize=False)),
                ('end_date_actual', models.DateField(null=True)),
                ('end_date_input', models.DateField(null=True)),
            ],
            options={
                'db_table': 'job_update_end',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='job_update_start_mock',
            fields=[
                ('service_ord', models.BigIntegerField(db_column='SERVICE_ORD')),
                ('job_update_id', models.BigIntegerField(db_column='Jobupdateid', primary_key=True, serialize=False)),
                ('cause_of_delay', models.CharField(db_column='Cause_of_Delay', max_length=50)),
                ('start_date_actual', models.DateField()),
                ('start_date_input', models.DateField()),
            ],
            options={
                'db_table': 'job_update_start',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='job_update_complete',
            options={},
        ),
        migrations.AlterModelOptions(
            name='job_update_end',
            options={},
        ),
        migrations.AlterModelOptions(
            name='job_update_start',
            options={},
        ),
        migrations.RemoveField(
            model_name='job_update_complete',
            name='job_update_id',
        ),
        migrations.AlterField(
            model_name='job_update_complete',
            name='job_complete_input',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job_update_complete',
            name='mal_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job_update_complete',
            name='service_ord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.ip220610cleaned'),
        ),
        migrations.AlterField(
            model_name='job_update_end',
            name='end_date_actual',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job_update_end',
            name='end_date_input',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job_update_end',
            name='job_update_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.job_update_start'),
        ),
        migrations.AlterField(
            model_name='job_update_end',
            name='service_ord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ip220610cleaned'),
        ),
        migrations.AlterField(
            model_name='job_update_start',
            name='cause_of_delay',
            field=models.CharField(choices=[('A/W SPARE', 'A/W SPARE'), ('A/W FACILITY', 'A/W FACILITY'), ('A/W OTHER JOB', 'A/W OTHER JOB'), ('OTH', 'OTH'), ('AWAIT UNIT ACCEPT', 'AWAIT UNIT ACCEPT'), ('MULTIPLE FAULTS', 'MULTIPLE FAULTS')], db_column='Cause_of_Delay', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job_update_start',
            name='service_ord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ip220610cleaned'),
        ),
        migrations.AlterField(
            model_name='job_update_start',
            name='start_date_actual',
            field=models.DateTimeField(db_column='startdate_actual', null=True),
        ),
        migrations.AlterField(
            model_name='job_update_start',
            name='start_date_input',
            field=models.DateTimeField(db_column='startdate_input', null=True),
        ),
        migrations.AlterModelTable(
            name='job_update_complete',
            table=None,
        ),
        migrations.AlterModelTable(
            name='job_update_end',
            table=None,
        ),
        migrations.AlterModelTable(
            name='job_update_start',
            table=None,
        ),
    ]
