# Generated by Django 3.2.13 on 2022-06-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20220620_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_update_complete',
            new_name='JobUpdateComplete',
        ),
        migrations.RenameModel(
            old_name='job_update_end',
            new_name='JobUpdateEnd',
        ),
        migrations.RenameModel(
            old_name='job_update_start',
            new_name='JobUpdateStart',
        ),
    ]
